### ISSUE TITLE
GTX 1080 Performances

### ISSUE THREAD

**Issue by Marplex** [funakoshi2718/funakoshi-miner#1]
Hi, exactly how many sol/s do you get with the GTX 1080? Is it overclocked?
Thanks.

**Comment by funakoshi2718** [comment]
The Pascal GPU's auto manage the clock as a function of load on device (except for the memory clock).
funakoshiMiner doesn't change the clock (no overclocking).

The sol/s changes all the time.
For GTX 1080 some of them are above 500 and some just bellow 500.

You are welcom to check, but remember that the pool estimate determines your earnings.
When you compare miner programs you should check what the pool says about their share
overtime (the pool changes its estimate all the time).

The funakoshiMiner writes to log each 15 seconds the the exact avarage sols/sec during the last 15 secs.
