### ISSUE TITLE
CUDA error 'CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by anthony19114** [funakoshi2718/funakoshi-miner#10]
03:53 AM ethos@c522e5 192.168.0.12 [miner disallowed] /home/ethos # ./funakoshiMiner -u t1tmnd5Ju6HWbNqx42iMgTPGitSaQtvtjwsF -l pool.com:2222 -cd 0 1 2 3 4

[2018-Apr-07 03:53:35] CUDA error 'CUDA driver version is insufficient for CUDA runtime version' at line 61
03:53 AM  # nvidia-smi
Sat Apr  7 03:54:25 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90

Driver 384.90, using cuda 9.0.

Only work for 390?

**Comment by funakoshi2718** [comment]
You should update your driver.
The error msg says that the driver is too old for cuda 9.

**Comment by funakoshi2718** [comment]
If you downloaded new driver maybe you should now download cuda 9.1

**Comment by anthony19114** [comment]
Just to let you know, then I will delete the Issue. 384 driver and cuda 9.0 are the best for mining equihash, and many other algorithms. 9.1 has performance issues. This is an issue with the driver I presume. You could remove that portion of driver check, as I presume the code is based off nheqminer.. but if you really want to achieve maximum potential.. 384 + cuda 9.0 are the best combinations.

**Comment by funakoshi2718** [comment]
Version 2.6 of Funakoshi-Miner is compiled with Cuda 9.2
Please upgrade your Cuda runtime from [Nvidia-Website](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu)

**Comment by anthony19114** [comment]
Funakoshi, you happen to get an email from me?

**Comment by funakoshi2718** [comment]
Sorry Anthony, but I am not interested.

**Comment by anthony19114** [comment]
Understandable, adieu
