### ISSUE TITLE
API

### ISSUE THREAD

**Issue by BobbyGR** [funakoshi2718/funakoshi-miner#13]
Hello - I had a user of AIOMiner ask me about this miner application.  Do you have any way of implementing an API to pull down stats?  Feel free to tag this as a Feature Request if not.  Looking forward to seeing this in action.

**Comment by funakoshi2718** [comment]
I will add api in the next release.

**Comment by BobbyGR** [comment]
Thanks, again looking forward to seeing how this project moves forward.  Also, with your releases any chance you can just zip up all of those files vs placing them there individually? When a user downloads the miner it will snag from your github and would be nice to have a package.  If not, no worries I can work around it.

**Comment by funakoshi2718** [comment]
Will do that in next release.
