### ISSUE TITLE
v2.2 vs 2.1

### ISSUE THREAD

**Issue by StrobFX** [funakoshi2718/funakoshi-miner#14]
Hi,
v2.1 was amazing and probably the fastest out there. but 2.2 is very slow. Like half the speed of 2.1 and also I am getting crashes.

**Comment by funakoshi2718** [comment]
What is the miner's memory requirement on your system?
Have you got enough memory?

**Comment by funakoshi2718** [comment]
Did you specify all 8 gpus in command line:  -cd 0 1 2 3 4 5 6 7

**Comment by StrobFX** [comment]
8 GB of ram and yes I specified all the gpu with -cd 0 1 2 3 4 5 6 7

**Comment by StrobFX** [comment]
No chrome

**Comment by funakoshi2718** [comment]
Are you over-clocking the gpu's?
If so maybe you should less over-clock for Funakoshi-Miner.

**Comment by funakoshi2718** [comment]
Jocelyn, please tell me your conclusions.
I hope that you solved the problem.

**Comment by StrobFX** [comment]
I use msi ab like this 90% 81tl +150cc +50mc 92fs

I will get back to it later cause I have some other work to do sorry.

**Comment by funakoshi2718** [comment]
My solver is not messing with the clocks (even if I wanted to,
in Pascal architecture Cuda doesn't allow you to change the
clocks, and I am not using lower-level api's).
However maybe because Funakoshi Miner is faster than EWBF,
you should start with low over-clocking and gradually increase it.
