### ISSUE TITLE
Stream truncated

### ISSUE THREAD

**Issue by saroshpatel09** [funakoshi2718/funakoshi-miner#16]
I am using this line for my NVidia cuda devices on my windows 10 pc 

funakoshiMiner -cd 0 1 -l zec.suprnova.cc:2142 -u Wallet.Worker password
 

Comes stream truncated

what am I doing wrong..?

help pls

**Comment by funakoshi2718** [comment]
Try using port 2242 which is the ssl port for zec.suprnova.
No need for password arg.
