### ISSUE TITLE
no stat viewing

### ISSUE THREAD

**Issue by saroshpatel09** [funakoshi2718/funakoshi-miner#17]
The miner is running as smoothly as it possibly can and thank you for the earlier assistance.
But i am not able to view the hashrate nor has the balance in my account on suprnova increased
inspite of mining for 3 days at a stretch.

Pls help

**Comment by funakoshi2718** [comment]
You should pass your account-name as value of -u argument when running funakoshiMiner.
The miner writes to the console if the specified user-name is authorized by the pool or not.
Maybe you have passsed a wrong user-name.
Please rerun the miner and check.

In suprnova there are a few pools: zec, zcl, zen, btg, ...
You should login to the correct pool and look at your account in that pool.

**Comment by funakoshi2718** [comment]
Very important !!!!!

In your suprnova account you must create a worker and specify that worker to the miner.
Lest suppose your user-name at suprnova is user12 and you just created a worker named worker12,
you should specify:     -u user12.worker12

**Comment by saroshpatel09** [comment]
Thanks Man..!!!!
Silly mistake by me..!!
Cheers
and awesome miner super stable
