### ISSUE TITLE
ZCL on Miningpoolhub not working

### ISSUE THREAD

**Issue by phenomeus** [funakoshi2718/funakoshi-miner#2]
hi, I'm testing your miner, but can't get it to work with ZCL on MPM:
this is the address:

europe.ethash-hub.miningpoolhub.com:20575

its stating that this pool is not supported.

**Comment by funakoshi2718** [comment]
You should use the domain
equihash-hub.miningpoolhub.com instead of
ethash-hub.miningpoolhub.com

**Comment by phenomeus** [comment]
sorry, you are totally right. now its running. my bad, thank you
