### ISSUE TITLE
LuckPool

### ISSUE THREAD

**Issue by hellcatz** [funakoshi2718/funakoshi-miner#20]
We have enabled a new stratums for LuckPool on a new domain (luckpool.net).
Please note, that new subdomains may also show up as we add more stratum servers.
New Stratums: eu.luckpool.net &amp; na.luckpool.net
Future: eu-west.luckpool.net, na-west.luckpool.net, ap.luckpool.net

...
[2018-Apr-28 12:22:44] [MINER] Using pool: na.luckpool.net
[2018-Apr-28 12:22:44] [MINER] Pool: na.luckpool.net is not yet supported.
Current version of funakoshi solver
supports the following equihash pools:
   slushpool, supernova, flypool, nanopool, miningspeed,
   coinmine, miningpoolhub, nibirupool, luckpool.

**Comment by funakoshi2718** [comment]
Domain luckpool.org is currently supported.
I will add support for domain luckpool.net in next release.
