### ISSUE TITLE
Release in zip archive

### ISSUE THREAD

**Issue by Cage1121** [funakoshi2718/funakoshi-miner#21]
Hi 

Could you please make a zip archive for Windows release? Just like [xmrig](https://github.com/xmrig/xmrig/releases).

Thanks.

**Comment by nerdatwork** [comment]
Seriously that is common sense.

**Comment by Twente-Mining** [comment]
+1

**Comment by BARUCHER777** [comment]
+1 AND full instructions or param`s

**Comment by Twente-Mining** [comment]
he/she won't, he/she won't even reply.

**Comment by funakoshi2718** [comment]
I have added a zip file plus a script-file.
