### ISSUE TITLE
Titan V Support

### ISSUE THREAD

**Issue by izhekov** [funakoshi2718/funakoshi-miner#22]
I tried a couple of versions whenever they work on Titan V but unsuccessful. With the latest one 2.6 it gives about 850 sol/s but in fact no accepted or rejected shares. Anyway if you plan to support it (which will be great) you shall target to go over 1000-1050 sols/s a this is currently achievable using EWFB miner with its algo 4 on Titan V.

**Comment by funakoshi2718** [comment]
Can you please show me the command-line you used and the firrst few lines of log?
