### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by LexRiver** [funakoshi2718/funakoshi-miner#24]
- how to show the temperature for each card in miner?
- what is "I/s" ?

**Comment by funakoshi2718** [comment]
Current temperatures are not yet written to log.
I am planning to add this feature, but currently I am working on more urgent features.
However you can limit max temperature using command line args.

The eqhihash algorithm executes iterations in a loop.
I/s means Iterations per Second. This is the more accurate
measure of speed. On average 1.8 solutions are found in each
iterations (but solutions per second varies a lot and can only be
effectively measured over a few hours period). The Iterations per
second is a more stable meassure of speed.

**Comment by LexRiver** [comment]
@funakoshi2718 ok thanks
