### ISSUE TITLE
Potential way to remove developer fee

### ISSUE THREAD

**Issue by Soham3-1415** [funakoshi2718/funakoshi-miner#27]
I started to create this issue earlier, but I prematurely submitted it.

I don't know much about mining and this software is closed source, so I'm basing this entirely on my knowledge of TLS and the information provided in the README. I noticed that the README says this miner uses SSL to prevent people using proxy servers to redirect funds. I don't know how to set up such a proxy server, but if the goal is to prevent clients from connecting to another server because the certificate doesn't match, are you making sure that the miner only approves specific certificates? Because it is very easy for someone to create a self-signed certificate and have their OS trust it. If the miner just makes sure that the certificate is approved by the OS, than people can easily send the miner through a proxy server, even with TLS. I have not tested this because I do not know enough about mining, but if this is a problem, I just wanted to alert you.

**Comment by funakoshi2718** [comment]
The miner verifies the certificate of the pool.
This certificate is only known to the pool.
Thus, proxy server can't impersonate to the pool.
Anyway thanks a lot.
