### ISSUE TITLE
Support for custom personalization string or bitcoinz

### ISSUE THREAD

**Issue by s0ftcorn** [funakoshi2718/funakoshi-miner#28]
Making the 8 characters of the personalization string user editable would make this miner usable for bitcoinz.

**Comment by funakoshi2718** [comment]
The miner auto fill the personalization string depending on the pool url.
For example when accessing pool btcz.suprnova.cc the pers string is auto
set to BitcoinZ and when accessing btg-testnet.miningspot.net with -144
pers string is auto set to BgoldPoW
