### ISSUE TITLE
Seem to be slower than DSTM

### ISSUE THREAD

**Issue by StrobFX** [funakoshi2718/funakoshi-miner#3]
Hi,

nice to see a new miner but right now it seems to be slower than DSTM (I still have to try it longer to get a good mean). I hope you can increase the speed a bit

But since it seems to be slower than DSTM. I would suggest to remove the dev fee or at least offer the option to remove the dev fee without slowing down the miner for those who set the dev fee to zero. At least until you can find a way to make it faster. That way you could maybe get a user base and then remove tha ability to set dev fee to zero once you get it faster. Or else I fear no one will use your miner.

**Comment by funakoshi2718** [comment]
Thanks Jocelyn
I have already improved performance by 1%  (release v1.1).
In the following days I will work hard and try to improve
performance even more.

**Comment by StrobFX** [comment]
ok sounds great I will try it.

**Comment by funakoshi2718** [comment]
Hey @StrobFX 
I am happy to inform you that after months of
hard work, Funakoshi miner is now the fastest
equihash cuda solver.

**Comment by StrobFX** [comment]
Wow! how much faster?

**Comment by StrobFX** [comment]
On my Titan Xp collector's edition, v2.1 seems to add 50 sol/s from v1.2

**Comment by funakoshi2718** [comment]
My miner reports true meassured hashes/s and sol/s. dstm also reports true values.
By between 5 to 20 sol/s for 1080, I meant compared to dstm, not compared to v1.2.
Thanks very much for sharing your findings with me.

**Comment by funakoshi2718** [comment]
I would like to add that you are very kind, thanks.

**Comment by StrobFX** [comment]
Because I'm also a Funakoshi Sensei fan!

**Comment by funakoshi2718** [comment]
You are right, thanks.
I haven't previously run my miner on 1060 and it is slower.
I have started working on improving performance for 1060.
When finished I will publish a new release.

**Comment by tech3ric** [comment]
i'm looking forward..thanks

**Comment by funakoshi2718** [comment]
I have improved the performance of Funakoshi-Miner on GTX 1060.

**Comment by kire3** [comment]
nice..ill try and let you know..

**Comment by kire3** [comment]
hi, i'm getting an error on my GTX 1060..already upgraded with latest driver. 390.59

CUDA error 'CUDA driver version is insufficient for CUDA runtime version' at line 61

**Comment by funakoshi2718** [comment]
Please upgrade Cuda runtime from Nvidia website:

    https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu

**Comment by funakoshi2718** [comment]
The error msg 'CUDA driver version is insufficient for CUDA runtime version' is returned by
Cuda and not by my code. This error means that Nvidia driver is too old or that Cuda runtime
is too old. One of them need to be upgraded. On my ubuntu I only upgraded the Cuda runtime
not the driver and it worked.

Release v2.6 of Funakoshi-Miner is compiled with Cuda 9.2
If your Cuda runtime is too old you need to upgrade it from
[Nvidia website](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu) 

If your driver is too old you need to [upgrade it](http://www.nvidia.com/Download/index.aspx?lang=en-us)

**Comment by tech3ric** [comment]
Hi, Im still getting the same error after upgraded to the latest Cuda and Nividia drivers. Btw, Im using GTX1060 3Gb. Could this be the reason of this error?

**Comment by funakoshi2718** [comment]
I don't think that the reason is the memory size otherwise the error would have been: out of memory.

I have successfuly run the current version of the miner on 2 different machines with GTX 1060 6GB,
one of them my physical PC and the other a cloud machine.  In both cases all I had to
do was to upgrade the Cuda runtime from Nvidia website.

I have no clue why you get  'CUDA driver version is insufficient for CUDA runtime version'.

**Comment by tech3ric** [comment]
Hi, finally its working now with nvidia driver 396.24 and cuda 9.2. But it's still slow for GTX1060 3Gb.

**Comment by funakoshi2718** [comment]
Thanks for notifying me.
Can you tell me how much I/secs (iterations per second, not solves per second) Funakoshi-Miner reports
on your system compared to the competition. The speed is determined by I/secs because solves per
seconds changes all the time and not stable and thus only avarage over a few hours should be checked. But Interations  per seconds is stable and can be used for checking performance. Please tell me the avarage reported  I/s over 1 minutes.

**Comment by tech3ric** [comment]
Hi, Here is my average. 

[2018-May-27 12:46:39] [MINER] Received new job #e008daca0b14f3d29609
[2018-May-27 12:46:55] [GPU-0 (15 sec)] 154 I/s, 285 Sols/s
[2018-May-27 12:46:55] [GPU-1 (15 sec)] 157 I/s, 291 Sols/s
[2018-May-27 12:46:55] [GPU-2 (15 sec)] 144 I/s, 260 Sols/s
[2018-May-27 12:46:55] [GPU-3 (15 sec)] 144 I/s, 271 Sols/s
[2018-May-27 12:46:55] [GPU-4 (15 sec)] 142 I/s, 271 Sols/s
[2018-May-27 12:46:55] [GPU-5 (15 sec)] 146 I/s, 281 Sols/s
[2018-May-27 12:46:55] [TOTAL (15 sec)] 887 I/s, 1659 Sols/s, 0 Accepted, 0 Rejected

Thanks

**Comment by funakoshi2718** [comment]
You are right. I need to improve the speed of my miner on GTX 1060.
There was a big jump but more is needed.

**Comment by tech3ric** [comment]
I'll wait for your next release. If possible please include the Temp and Power on the output. Thanks
