### ISSUE TITLE
Not working on BTG Suprnover

### ISSUE THREAD

**Issue by Gilly1970** [funakoshi2718/funakoshi-miner#30]
Keeps connecting to port 8817 even when setting to new port 8866

**Comment by DrNesto** [comment]
I have the same problem, don't working on Suprnova pool.

**Comment by gellfuen** [comment]
I still have the same with version 3.2 - no mining with suprnova pool!

**Comment by funakoshi2718** [comment]
suprnova disabled port 8817 after the fork.

I have requested them to enable it.
I will tell you when its done.

Unfortunately I am on vacation until 19 July so I wont be
able to fix the miner to use the other port befure I return.

I hope that suprnova will enable port 8817 soon and the problem will be auto resolved.

**Comment by Gilly1970** [comment]
Now working thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
