### ISSUE TITLE
Invalid Shares

### ISSUE THREAD

**Issue by paniccode** [funakoshi2718/funakoshi-miner#31]
5 1080ti, windows 10, no overclock, and tried under clock, all bad shares... 144,5 algo

**Comment by funakoshi2718** [comment]
try adding -144 command line argument
This tells the miner to use the 144,5 algo

**Comment by paniccode** [comment]
Yes I already did. 

On July 5, 2018 7:00:33 PM EDT, funakoshi2718 <notifications@github.com> wrote:
>try adding -144 command line argument
>This tells the miner to use the 144,5 algo
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/funakoshi2718/funakoshi-miner/issues/31#issuecomment-402876383

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by funakoshi2718** [comment]
Can you show me the command line

**Comment by funakoshi2718** [comment]
If you are using release prior to 3.2 the -144 must precede the temp limit args. This bug was fixed in release 3.2

**Comment by paniccode** [comment]
This is my command line
funakoshiMiner -144 -l us.btgpool.pro:3857 -u xxx.xxx

**Comment by funakoshi2718** [comment]
Btgpool have changed the port to 1445.
Funakoshi miner uses the old port 3857
which doesn't support 144,5 on btgpool.
I will be able to update the software to use port 1445 only when I return from vacation on 20 July.
Until than Funakoshi miner will not be able to support btgpool.
Sorry.

**Comment by paniccode** [comment]
Thx your for your help have a good vacation.

On July 5, 2018 11:37:23 PM EDT, funakoshi2718 <notifications@github.com> wrote:
>Btgpool have changed the port to 1445.
>Funakoshi miner uses the old port 3857
>which doesn't support 144,5 on btgpool.
>I will be able to update the software to use port 1445 only when I
>return from vacation on 20 July.
>Until than Funakoshi miner will not be able to support btgpool.
>Sorry.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/funakoshi2718/funakoshi-miner/issues/31#issuecomment-402916175

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by funakoshi2718** [comment]
I have checked the following commands:
    funakoshiMiner.exe -144 -l us.btgpool.pro:3857 -u xxx.xxx
         and
    funakoshiMiner.exe -144 -l us.btgpool.pro -u xxx.xxx

Both works fine.

btgpool.pro supports running equihash<144,5> on port 3857.
