### ISSUE TITLE
Add personalization string as command line parameter

### ISSUE THREAD

**Issue by heptacoin** [funakoshi2718/funakoshi-miner#38]
To support more new equihash 144,5 coins, please add personalization string as command line parameter. For example HeptaCoin use HeptaPoW, BitcoinZ use BitcoinZ and other coins use standard ZcashPoW.
Thanks

**Comment by funakoshi2718** [comment]
Currently the supported coins and pools are hardcoded in the miner.
This is for supplying defaults parameter-values and auto correcting
port number mistakes. 
In a later version I will enable free selection of all parameters.

**Comment by funakoshi2718** [comment]
In release v4.5 the --pers argument is supported.
This enables mining any 144,5 coin.
