### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by JoinJoin** [funakoshi2718/funakoshi-miner#39]
CUDA error 'CUDA driver version is insufficient for CUDA runtime version' at line 50

everything else using CUDA seems to work except funakoshi-miner

`modinfo nvidia | grep "^version:" | sed 's/^version: *//;'`

returns: 390.48 

and I have NVIDIA CUDA Runtime Library libcudart9.1

Edit: I use Kubuntu 18.04

**Comment by funakoshi2718** [comment]
Funakoshi-Miner is compiled with CUDA runtime Library 9.2
Please try to upgrade to CUDA 9.2
