### ISSUE TITLE
Only way to get custom max-min temp settings for each gpu

### ISSUE THREAD

**Issue by Phoenix983** [funakoshi2718/funakoshi-miner#4]
funakoshiMiner.exe -cd 0 -temp-max 80 -temp-min 75 -cd 1 -temp-max 80 -temp-min 75 -cd 2 -temp-max 80 -temp-min 75 -cd 3 -temp-max 80 -temp-min 75 -cd 4 -temp-max 80 -temp-min 75 -l us1-zcash.flypool.org:3443 -u WALLET.Machine016 -p 10240

THAT IS THE ONLY WAY TO GET CORRECT TEMP MAX AND MIN WORKING ON EACH GPU, IF I SET -cd 0 1 2 3 4 AND JUST 1 TIME -temp-min 75 AND -temp-max 80 ONLY THE GPU 0 STORES THESE VALUES BUT NOT THE REST OF THE OTHER GPU'S, THEY GOT 0 VALUES ON BOTH MIN AND MAX TEMPS SETTINGS.

TESTED ON A 5 GPU'S 1060 RIG.

REGARDS.

**Comment by funakoshi2718** [comment]
Thanks Phoenix

I did that on purpose, to enable giving different temperature bounds for each gpu.
I should explain it clearly in the documentation (I forgot to do that).

However do you think that it is prefered to specify a single temperature bounds
that will be applied to all gpus. I can change it?

**Comment by funakoshi2718** [comment]
Thanks a lot for your comments.
They are most helpful.
I will implement your proposals in the following release.

**Comment by funakoshi2718** [comment]
Now following each -temp-max or -temp-min arg you can specify multiple values (one per each GPU).

Added new args:   -temp-max-all and -temp-min-all  (to enable specifying same bounds for all GPU's).

Colors are used on Linux terminals, but not yet on Windows.

Not yet added watchdog (I will do that later).
