### ISSUE TITLE
nvmlInit failed

### ISSUE THREAD

**Issue by Chakthi** [funakoshi2718/funakoshi-miner#42]
What does nvmlInit failed mean?  I plugged in all the info into the start.bat file for mining on Ethermine.org, but when I run the bat file, everything looks good until that pops up on the screen.  I am mining with an nVidia 1080ti, which the software properly detects, and even though that message is on the screen, the software appears to be going through the motions of mining, but nothing is actually occurring.

Can you help me with the info supplied, or do you need more info to identify the problem?

Thanks very much!

**Comment by funakoshi2718** [comment]
What coin are you mining?

Funakoshi-Miner can't mine ethereume.
It can mine zcash, bitcoingold, zencash, and all other equihash 200,9 and equihash 144,5 coins.

nvmlInit is used for initializing nvml.dll (which is used for equrying temperature of gpu).
You need the nvml.dll (you can download it from my repository).
