### ISSUE TITLE
nvmlInit failed

### ISSUE THREAD

**Issue by caesra** [funakoshi2718/funakoshi-miner#43]
During startup nvmlInit failed when using 2080 Ti.  

Tried varying algos and card arrangements.  Using current drivers. Not finding similar issue with other miners.

**Comment by funakoshi2718** [comment]
The miner needs the file nvml.dll  (used for querying gpu temperature).
The file can be downloaded from my github page, or from directory of 
coda runtime.
Put nvml.dll in the same directory as funakoshiMiner.exe

**Comment by funakoshi2718** [comment]
Have you instaled the cuda runtime from Nvidia website?

**Comment by caesra** [comment]
I have never needed to install anything from nVidia other than the current drivers.  What specifically are you suggesting I install?  The CUDA dev toolkit?

**Comment by funakoshi2718** [comment]
Try to use the nvml.dll supllied by nvidia instead of the file
that is supplied by me (which is an older version of nvml.dll).
Maybe they are no longer compatible.

The nvml.dll file should be located at:
    C:\Program Files\NVIDIA Corporation\NVSMI

I am not sure if it is put there when installing the driver or when installing coda toolkit.

**Comment by caesra** [comment]
Copying the dll from the nVidia folder allowed it to initialize (the date on theirs was 6 days older than the one you included).  Once it initialized it acted like it was working, but the GPUs were not doing anything.  The console showed 0 Sols/s and then after 4 job receipts it errored out with ‘CUDA error ‘unknown error’ at line 2270.

**Comment by funakoshi2718** [comment]
I currently have no access to a 2080 Ti gpu.
I can't check it out, sorry.
