### ISSUE TITLE
CUDA error 'invalid device ordinal' at line 61

### ISSUE THREAD

**Issue by tsing90** [funakoshi2718/funakoshi-miner#6]
it could not be run, and appeared the error "CUDA error 'invalid device ordinal' at line 61"
previously, the version I used was 0.3.3.
I know I need to update cuda to 9.0, but after updating cuda, cudnn, and nvidia driver, still not working.
environment:
windows 10
nvidia TitanXp
nvidia cuda 9.0.5
nvidia driver v391

thank you for help

**Comment by funakoshi2718** [comment]
Can you please show me the command-line.
The argument -cd 0 1 3  for example selects devices 0 and 1 and 3.

**Comment by tsing90** [comment]
thanks for your quick reply.
I have one GPU, and I tried different command lines, such as "funakoshiMiner.exe -l eu1-zcash.flypool.org:3333 -u tMyWalletAddress.rig1 -p x -f log.txt -cd 0 1 2", but always was not able to run.
It seemed the gpu device could not be detected, but with no clue of reason

**Comment by funakoshi2718** [comment]
If you have only 1 GPU then you should pass the argument -cd 0
because you don't have gpu's 1 and 2 but only gpu 0.

**Comment by tsing90** [comment]
Solved !
yes, I modified as '-cd 0' and changed the port to 3443, then worked !
actually, the previous version (0.3.3) didn't throw an error when I kept '--cuda_devices 0 1 2 3', so I thought it might do not matter

thank you very much , appreciated !
