### ISSUE TITLE
Truncated Error

### ISSUE THREAD

**Issue by paniccode** [funakoshi2718/funakoshi-miner#7]
Mining on Suprnova 
Stream Truncated error , reconnecting to pool

**Comment by funakoshi2718** [comment]
Can you show me the command-line, maybe you mispelled the pool domain or supplied non ssl port.

**Comment by paniccode** [comment]
funakoshiMiner -cd 01 -l zen.suprnova.cc:3618 -u fish.mainti -p xx

**Comment by funakoshi2718** [comment]
Try to use ssl port number 3621
Also for mining with card number 0 use -cd 0
If you have 2 gpu cards use -cd 0 1   (not -cd 01).
Also fish.mainti  is unauthorized worker.
No need to pass password  -p arg.

**Comment by funakoshi2718** [comment]
The miner can't read and report the power consumption using nvml (nvidia library for management).
Maybe something went wrong during gpu-driver or cuda installation.
Maybe you are using too old cuda version.
This error msg should not interfere with mining.
