### ISSUE TITLE
Nvidia 1070 getting 410 Sol/S in comparison to 440 I am getting on DSTM

### ISSUE THREAD

**Issue by lion8000** [funakoshi2718/funakoshi-miner#8]

**Comment by funakoshi2718** [comment]
Strange. I specificaly checked gtx 1070 and got more solves than dstm.

**Comment by funakoshi2718** [comment]
Did you took avarage over time or just the first reported number?
You should look at the avarage over time.

**Comment by lion8000** [comment]
The Average Overtime. I am using DSTM with OC 70% Voltage, Core +60 and Memory 800 and getting AVG 435. Using Funakoshi is getting me 410.

**Comment by funakoshi2718** [comment]
On gtx 1070 I am getting for Funakoshi 225 hashes/s and 434 sol/s without OC which is more than dstm.
I have no clue why you get different numbers.
